# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5637862d1c46fa6b46175901ed093fbff441519e3dcf7cf130280b771b1a1f8f0bf100141e1a98aa79041fc7d602f3e3eca78db722325e049f859e5df4ea6db

test:
  secret_key_base: 3febfb1e0596bab09b98777240b06f18848edaa8ae0449fffa5c1f81a4e5b570e3e98f5427ed144b64ae3f10d2178d15b11413f1e2b0ee6003d70d42fcecac97

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
